### ISSUE TITLE
Installable progressive webapp

### ISSUE THREAD

**Issue by kowalski7cc** [flipperdevices/my.flipper.net#10]
Support for Chrome PWA, so site can work like an app and have offline functionality on Chromebooks

**Comment by Slipn3r** [comment]
Why would you need that? We don't have plans on this, though you can add PWA support yourself if you like. Quasar framework offers PWA support out of the box, check out the docs.

**Comment by kowalski7cc** [comment]
I have a Chromebook, and qFlipper doesn't play really nice with crostini
