### ISSUE TITLE
Unable to browse files

### ISSUE THREAD

**Issue by UberGuidoZ** [flipperdevices/my.flipper.net#5]
Trying to navigate the files, it will not go past the top level. When I click a folder, it appears in the address bar but won't navigate to it. And if I continue to click around, it continues to add the name to the address bar. This did not use to be a problem.

1 out of 5 times, it will let me browse a folder and see files. Coming out of the folder then shows the same behavior.

Tested with the following (same issue)
- Chrome v103.0.5060.114 (Official Build) (64-bit)
- Edge v103.0.1264.49 (Official build) (64-bit)

https://user-images.githubusercontent.com/57457139/178096388-559cde60-79f7-4c06-8220-b82ec1656d09.mp4

.

**Comment by Slipn3r** [comment]
Thank you for the report, can't reproduce so far.
What is your current Flipper firmware version? Does this issue occur while using file manager in qFlipper?
Most likely there should be a verbose error in browser console, please check it out.

**Comment by UberGuidoZ** [comment]
Firmware installed ([RogueMaster](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/releases/tag/0.62.1-0711-RMv2))

![Firmware](https://user-images.githubusercontent.com/57457139/178659749-379383f4-9aa1-4986-b588-9cd28f98eb3c.png)

I am not having any issues in qFlipper. Here's what shows in the browser console:

![Browser_Console](https://user-images.githubusercontent.com/57457139/178660380-d8a65b20-d36a-4c15-877d-1f88b66f20e7.png)

I am also trying incognito for the screenshot above (same issue.) I have since flashed Official dbf1d9f3 and **am not** having the same issue. Looks like I need to bring this up with Unleashed.RogueMaster. Thank you. =)
